### ISSUE TITLE
CLI: Init should explain why sudo is required.

### ISSUE THREAD

**Issue by OR13** [transmute-industries/transmute#109]
asks for password to modify `/etc/hosts` but does no explain why.

We basically just need an echo here:

https://github.com/transmute-industries/transmute/blob/master/scripts/initializer#L147

**Comment by OR13** [comment]
# Settings Up Transmute on a MacMini From Scratch

What I did to setup transmute on a brand new mac mini.


### Install the development environment dependencies

```
curl -Ls https://git.io/transmute_bootstrap | bashcurl -Ls

```



### Use the transmute cli to setup the rest.
```
transmute k8s provision-minikube mac-mini
```

**Comment by daniel-yavorovich** [comment]
* we can run all script by sudo and user need input password only one
* we can create bash function with privileged operation and call this function via sudo

what is way to use?

**Comment by OR13** [comment]
@daniel-yavorovich sorry for the delay responding to this I have notifications off on github it seems.

I think the best use case is to minimize sudo use, as much as possible. 

The bootstrap will require sudo for some parts:

https://github.com/transmute-industries/transmute/blob/master/bootstrap

and the transmute cli will require sudo since minikube needs to needs to run as root when vm driver is none.

https://github.com/transmute-industries/transmute/blob/feat/add-okta-login-to-cli/packages/transmute-cli/src/commands/provision.js#L10

I'm ok having the user enter their password when needed, I just want them to be prompted to they know why.

I think for what these scripts are doing, the best way to handle this is to minimize sudo, and only use it where absolutely necessary, and when we do that clearly communicate why (for example altering /etc/hosts).

I cleaned up the travis ci side of this a lot in this PR: https://github.com/transmute-industries/transmute/pull/141

I feel slightly uncomfortable running the whole script as sudo, seems like its better to use it sparingly.

**Comment by daniel-yavorovich** [comment]
https://github.com/transmute-industries/transmute/blob/feat/add-okta-login-to-cli/packages/transmute-cli/src/commands/provision.js#L10 - this link not found

**Comment by OR13** [comment]
Sorry, I reorganized the commands hoping to make it easier to collaborate:

https://github.com/transmute-industries/transmute/tree/master/packages/transmute-cli/src/commands

**Comment by daniel-yavorovich** [comment]
@OR13 

```$ ls -ls /etc/hosts
8 -rw-r--r--  1 root  wheel  376 May 29 18:42 /etc/hosts```

/etc/hosts has administrator only access for write in any unix-systems(linux, mac, freebsd) and required sudo fo change.

Please clarify task - where I need integrate sudo? Or my task is check https://github.com/transmute-industries/transmute/blob/master/packages/transmute-cli/src/commands/init/initializer and check sudo usage?

Thank you.

**Comment by OR13** [comment]
The request is to review the use of sudo throughout the initialization process:

```
source <(curl -Ls https://git.io/transmute_bootstrap)
transmute k8s provision-minikube my-cluster
transmute k8s init my-cluster
```

minimize the use of sudo as much as possible.

For cases's where it 100% necessary (such as modifying hosts) make it clear why the user is being prompted for their password.

This flow is currently being tested in travis ci, and has been tested locally on osx.

I'm asking for a review of how it works, suggestions for improvements, removing of any unnecessary sudo use, and clear warnings to the user for cases where sudo is needed.

**Comment by daniel-yavorovich** [comment]
Where is located https://git.io/transmute_bootstrap in repo?

**Comment by OR13** [comment]
If you click the link, it will show you, its in root level of master branch:

https://raw.githubusercontent.com/transmute-industries/transmute/master/bootstrap

**Comment by daniel-yavorovich** [comment]
@OR13 thank you.

**Comment by daniel-yavorovich** [comment]
I have created pull request: https://github.com/transmute-industries/transmute/pull/169

Also I want to offer you the use of Ansible instead of monolithic bash-script. This will improve portability, add cleanliness and simplicity of code support.

Ansible can also bootstraping, via `curl | bash -`
