### ISSUE TITLE
Bootstrap script not installing transmute cli on Mac

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute#132]
After running `curl -Ls https://git.io/transmute_bootstrap | bash`, I get `-bash: transmute: command not found` when trying to use the cli.

**Comment by OR13** [comment]
Seems like the transmute-cli did not install correctly.

**Comment by OR13** [comment]
I'm trying to reproduce.

**Comment by OR13** [comment]
Tested this, and it was working after bootstrap fixes, closing
