### ISSUE TITLE
Cluster name is never used

### ISSUE THREAD

**Issue by eolszewski** [transmute-industries/transmute#181]
https://github.com/transmute-industries/transmute/blame/master/packages/transmute-cli/src/commands/init/initializer#L3

**Comment by luenix** [comment]
This is addressed for `transmute k8s provision-minikube` and `transmute k8s init` commands as of PR #198.

Left to be done: address other Transmute CLI commands by removing clusterName usage for the time being.  Eventually in the near-ish future Transmute CLI should maybe support naming the cluster, but there's no benefit as of right now.
