### ISSUE TITLE
Docs link is dead in Transmute Framework README

### ISSUE THREAD

**Issue by gjgd** [transmute-industries/transmute#212]
This link https://github.com/transmute-industries/transmute/blame/master/packages/transmute-framework/README.md#L3 is dead

**Comment by OR13** [comment]
https://docs.transmute.industries/transmute-framework/0.2.0-alpha.5/index.js.html

Probably the link is malformed

**Comment by OR13** [comment]
also, we should rebuild our docs and republish

**Comment by gjgd** [comment]
how does one do that?

**Comment by OR13** [comment]
see package.json... the docs are built, and when commited to the docs directory on master, they will be published. npm package publish is done via `npm publish`, you must be granted access to do this for each npm package.
