### ISSUE TITLE
Directory transmute-config not exist

### ISSUE THREAD

**Issue by daniel-yavorovich** [transmute-industries/transmute#43]
I have some problems with local deploy transmute:
 
```
$ npm run setup
...
[yn]y
ok, I will copy the example environment file to transmute-config/.env
cp: ./transmute-config/.example.env: No such file or directory
Would you like to edit the environment file?
[yn]
```

```
$ curl -Ls https://raw.githubusercontent.com/transmute-industries/transmute/master/bootstrap | bash
...
bash: line 475: cd: /Users/daniel/.transmute/git/transmute/transmute-config: No such file or directory
```

Each installer try to find transmute-config dir in root directory of repository, but this dir doest not exist. 

Where I can find config example? I have found 2 dirs:
* `./packages/transmute-framework/src/transmute-config`
* `./packages/transmute-dashboard/src/transmute-config`

But I think that this is not what I need.

Thank you.

**Comment by daniel-yavorovich** [comment]
Also I did not found this file in git history:

```Mac-mini:transmute daniel$ git branch
* master
Mac-mini:transmute daniel$ git log --full-history -- transmute-config/.example.env
Mac-mini:transmute daniel$```

**Comment by OR13** [comment]
@daniel-yavorovich thanks for reporting this!

I'm pretty sure that env file is not being used anymore, and our local setup script is out of date.

I'll ping you when we fix this.

**Comment by daniel-yavorovich** [comment]
JFYI: `.env` file is used in the installation script https://github.com/transmute-industries/transmute/blob/master/setup/0.init.sh#L77

**Comment by OR13** [comment]
thanks for the direct link, I'm working on a fix.

**Comment by OR13** [comment]
yep here is a sanitized old env file.

```
export MINIKUBE_IP=$(minikube ip)
export KONG_NGROK_HOST='your ngrok host'
# export KONG_NGROK_PROXY_URL='your kong exposed by ngrok'
export KONG_CONSUMER_USERNAME='bob@example.com'
export KONG_CONSUMER_ID='0'

export OKTA_HOSTNAME='you.oktapreview.com' 
export OUTPUT_FILE='./setup/okta.pem'

export OKTA_CLIENT_ID='SECRET'
export OKTA_CLIENT_SECRET='SECRET'

export OKTA_USERNAME='SECRET'
export OKTA_PASSWORD='SECRET'

export SECONDS_FOR_KONG=200

OKTA_TEST_USER_USERNAME='SECRET'
OKTA_TEST_USER_PASSWORD='SECRET'
```

This is what got moved / removed.

**Comment by OR13** [comment]
Yep, I broken this when trying to clean things up.

When https://github.com/transmute-industries/transmute/pull/45 passes CR and is merged this should be resolved.

**Comment by OR13** [comment]
@daniel-yavorovich This should be fixed now, still may require some okta setup to get the JWT protection enabled in kong correctly.

Its roughly documented in the script, but you can read more about it here:

https://developer.okta.com/authentication-guide/implementing-authentication/password
