### ISSUE TITLE
truffle:test failed

### ISSUE THREAD

**Issue by daniel-yavorovich** [transmute-industries/transmute#46]
Hello! I have problem with truffle tests running:

```
$ lerna run --scope transmute-framework truffle:test
...
Error parsing /Users/daniel/.transmute/git/transmute/packages/transmute-framework/contracts/EventStore.sol: ParsedContract.sol:13:16: ParserError: Expected identifier, got 'LParen'
    constructor() public {
               ^
Compilation failed. See above.
...
```

```
$ git branch
* master
$ helm ls ganache
NAME   	REVISION	UPDATED                 	STATUS  	CHART            	NAMESPACE
ganache	1       	Mon May  7 01:28:26 2018	DEPLOYED	ganache-cli-0.1.0	default
```

This is deploy/configuration issue (maybe need use other software version) or code bug?

Thank you!

**Comment by eolszewski** [comment]
Hey Daniel,

You may want to check your truffle / solidity version.

Mine are 
```
Truffle v4.1.3 (core: 4.1.3)
Solidity v0.4.19 (solc-js)
```

**Comment by OR13** [comment]
yep, thats definitly a solc version issue. updating truffle should resolve it.

**Comment by eolszewski** [comment]
We no longer have a transmute-eventstore package and contracts have been migrated to transmute-contracts. If you have trouble deploying those contracts, please open another issue.
