### ISSUE TITLE
Broken ipfs directory permissions

### ISSUE THREAD

**Issue by daniel-yavorovich** [transmute-industries/transmute#51]
OS: MacOS X High Sierra 0.13.4 (17E199)
Minikube version: v0.24.1
Kubernetes 1.10

DaemonSet has run params:
```
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
```

But mounted directory owned by root. 

```
$ kubectl logs decentralized-storage-ipfs-0
ipfs version 0.4.9
Error: /data/ipfs is not writeable by the current user
initializing IPFS node at /data/ipfs
```

**Comment by OR13** [comment]
This is interesting. we don't see this error on gke.

we have openebs on gke... potentially we will encounter this same error when running locally.

**Comment by OR13** [comment]
I wonder if this is K8s 1.10 related

**Comment by OR13** [comment]
This has been reproduced, @joshuacox to report back.

**Comment by OR13** [comment]
I believe this is K8s version related, see https://github.com/transmute-industries/transmute/issues/96

closing.
