### ISSUE TITLE
Helm tuning for local install

### ISSUE THREAD

**Issue by daniel-yavorovich** [transmute-industries/transmute#64]
By default helm is not response from host machine by http/8080:

```
Error: Get http://localhost:8080/version: dial tcp 127.0.0.1:8080: connect: connection refused
```

Please add to script workaround for allow access to helm:

```
kubectl -n kube-system patch deployment tiller-deploy -p '{"spec": {"template": {"spec": {"automountServiceAccountToken": true}}}}'
```

**Comment by joshuacox** [comment]
Let me investigate this and figure out why you are seeing this issue and no one else is.

**Comment by OR13** [comment]
This issue seems very stale, I was not able to reproduce.
